services:
  signature_generator:
    image: openfn/ai-gen/signature_generator:v1.0.0
    build:
      context: ./services/signature_generator
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./services/signature_generator/.env.example

  code_generator:
    image: openfn/ai-gen/code_generator:v1.0.0
    build:
      context: ./services/code_generator
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./services/code_generator/.env.example

  inference:
    image: openfn/ai-gen/inference:v1.0.0
    build:
      context: ./services/inference
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./services/inference/.env
    # tty: true
    # Uncomment the following lines to set environment variables in place of env_file
    # environment:
    #   - OPENAI_API_KEY=sk-YOUR-API-KEY-HERE
    #   - HF_ACCESS_TOKEN=hf_YOUR-API-KEY-HERE
