name: Build and push Docker images

on:
  push:
    tags: "@openfn/ws-apollo@**"

jobs:
  build-and-push-worker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Manipulate tag for docker
        id: branch_name
        run: |
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
          echo Source Tag: $SOURCE_TAG

          VERSION_TAG=${SOURCE_TAG#@openfn/apollo}
          echo Version Tag: $VERSION_TAG

          DOCKER_TAG=${VERSION_TAG#@}
          echo Docker Tag: $DOCKER_TAG

          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          target: apollo
          tags: |
            openfn/apollo:latest
            openfn/apollo:v${{ env.DOCKER_TAG }}
